// Pisces Moon OS — IDE Main Controller
// Copyright (C) 2026 Eric Becker / Fluid Fortune
// SPDX-License-Identifier: AGPL-3.0-or-later

let editor       = null;
let emulator     = null;
let builder      = null;
let currentType  = "builtin";
let currentFile  = "my_app.cpp";
let currentFunc  = "run_my_app";

// ─────────────────────────────────────────────
//  CONSOLE
// ─────────────────────────────────────────────
function logConsole(msg, type = "") {
  const c = document.getElementById("console");
  const line = document.createElement("div");
  line.className = "line " + type;
  const t = new Date().toLocaleTimeString().split(" ")[0];
  line.innerHTML = `<span class="ts">[${t}]</span>${escapeHtml(msg)}`;
  c.appendChild(line);
  c.scrollTop = c.scrollHeight;

  // Trim to last 200 lines
  while (c.children.length > 200) c.removeChild(c.firstChild);
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function setStatus(msg, type = "") {
  const el = document.getElementById("status-msg");
  el.textContent = msg;
  el.className = type;
}

// ─────────────────────────────────────────────
//  API REFERENCE PANEL
// ─────────────────────────────────────────────
function renderAPI(filter = "") {
  const tree = document.getElementById("api-tree");
  tree.innerHTML = "";
  const f = filter.toLowerCase();

  for (const [cat, items] of Object.entries(PISCES_API)) {
    const matches = items.filter(item =>
      !f || item.name.toLowerCase().includes(f) || item.desc.toLowerCase().includes(f)
    );
    if (matches.length === 0) continue;

    const catDiv = document.createElement("div");
    catDiv.className = "api-cat";

    const lbl = document.createElement("div");
    lbl.className = "api-cat-label";
    lbl.textContent = cat;
    catDiv.appendChild(lbl);

    for (const item of matches) {
      const it = document.createElement("div");
      it.className = "api-item";
      it.title = item.desc;
      it.innerHTML = `<span class="api-item-name">${escapeHtml(item.name)}</span>`;
      it.onclick = () => {
        if (editor && !item.name.startsWith("//")) {
          const sel = editor.getSelection();
          editor.executeEdits("api-insert", [{
            range: sel,
            text: item.name,
            forceMoveMarkers: true,
          }]);
          editor.focus();
        }
      };
      catDiv.appendChild(it);
    }
    tree.appendChild(catDiv);
  }
}

// ─────────────────────────────────────────────
//  TEMPLATES
// ─────────────────────────────────────────────
function renderTemplateGrid() {
  const grid = document.getElementById("template-grid");
  grid.innerHTML = "";
  for (const [key, t] of Object.entries(TEMPLATES)) {
    const card = document.createElement("div");
    card.className = "template-card";
    card.innerHTML = `<h4>${escapeHtml(t.name)}</h4><p>${escapeHtml(t.desc)}</p>`;
    card.onclick = () => loadTemplate(key);
    grid.appendChild(card);
  }
}

function loadTemplate(key) {
  const t = TEMPLATES[key];
  if (!t) return;
  if (editor) editor.setValue(t.code);
  currentType = t.type;
  currentFunc = t.funcName;
  document.querySelectorAll(".seg").forEach(b => {
    b.classList.toggle("active", b.dataset.type === currentType);
  });

  const file = currentType === "elf" ? "my_module.cpp" : "my_app.cpp";
  document.querySelector(".file-item").textContent = "📄 " + file;
  document.querySelector(".tab.active").textContent = file;

  document.getElementById("modal-template").style.display = "none";
  setStatus(`Loaded template: ${t.name}`, "success");
  logConsole(`Template loaded: ${t.name}`, "info");
}

// ─────────────────────────────────────────────
//  EXPORT
// ─────────────────────────────────────────────
function exportCpp() {
  if (!editor) return;
  const src = editor.getValue();
  const file = currentType === "elf" ? "my_module.cpp" : "my_app.cpp";

  // Generate integration instructions
  const integration = currentType === "builtin"
    ? generateBuiltinIntegration()
    : generateElfIntegration();

  // Bundle as zip-like multi-file download via two clicks
  downloadFile(file, src);
  setTimeout(() => downloadFile("integration.txt", integration), 200);

  if (currentType === "elf") {
    setTimeout(() => downloadFile("my_module.json", JSON.stringify(TEMPLATES.elf_module.manifest, null, 2)), 400);
  }

  setStatus(`Exported ${file} + integration instructions`, "success");
  logConsole(`Exported: ${file}`, "info");
}

function generateBuiltinIntegration() {
  return `# Pisces Moon OS — Integration Instructions
# Built-in App: ${currentFunc}
#
# Generated by Pisces Moon IDE — fluidfortune.com

To integrate this app into the Pisces Moon firmware:

1. Place the .cpp file:
   src/my_app.cpp

2. Add declaration to include/apps.h:

   void ${currentFunc}();

3. In src/launcher.cpp, add a new APP ID after the highest existing one:

   #define APP_MY_APP   49   // (or next available number)

4. In src/launcher.cpp, add to the appropriate category array
   (TOOLS shown — change to COMMS, CYBER, GAMES, INTEL, MEDIA, or SYSTEM):

   { "TOOLS", "T", 0x8C00,
     { ...existing apps...,
       {"MY APP", APP_MY_APP} },
     <appCount + 1> },

5. In src/launcher.cpp launchApp() switch:

   case APP_MY_APP: ${currentFunc}(); break;

6. Build and flash:

   pio run -e esp32s3 -t upload

7. Test in the SDL2 emulator first (no flash needed):

   pio run -e sdl2 && .pio/build/sdl2/program

The same source compiles for both targets without changes.

# fluidfortune.com
# AGPL-3.0-or-later
`;
}

function generateElfIntegration() {
  return `# Pisces Moon OS — Integration Instructions
# ELF Module
#
# Generated by Pisces Moon IDE — fluidfortune.com

To deploy this ELF module:

1. Place the .cpp file in your ELF module project directory.

2. Compile against the Pisces Moon ELF API:

   pio run -e esp32s3

   Required compile flags (add to platformio.ini):
     -fPIC -mfix-esp32-psram-cache-issue --entry elf_main

3. Extract the .elf binary from .pio/build/esp32s3/

4. Place these on the SD card:

   /sd/apps/my_module.elf
   /sd/apps/my_module.json

5. Launch via SYSTEM → ELF APPS → My Module

The module loads into PSRAM at runtime. No firmware reflash needed.

# fluidfortune.com
# AGPL-3.0-or-later
`;
}

function downloadFile(name, content) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ─────────────────────────────────────────────
//  RUN PREVIEW
// ─────────────────────────────────────────────
function detectEntryFunction(src) {
  // Priority 1: ELF entry
  if (/extern\s+"C"\s+int\s+elf_main\s*\(/.test(src)) {
    return "elf_main";
  }
  // Priority 2: any void run_*() function
  const m = src.match(/\bvoid\s+(run_\w+)\s*\(\s*\)\s*\{/);
  if (m) return m[1];
  // Priority 3: fall back to currentFunc
  return currentFunc;
}

function runPreview() {
  if (!editor || !emulator) return;
  const src = editor.getValue();

  // Auto-detect entry function — handles pasted code where the user's
  // function is named differently than the active template.
  const funcName = detectEntryFunction(src);

  setStatus(`Transpiling ${funcName}() and starting preview...`, "info");
  logConsole("---- RUN ----", "info");
  logConsole(`Entry: ${funcName}()`, "info");

  const ok = emulator.run(src, funcName);
  if (ok) {
    setStatus("Preview running", "success");
    document.getElementById("btn-run").style.display = "none";
    document.getElementById("btn-stop").style.display = "inline-block";
  } else {
    setStatus("Preview failed — check console", "error");
  }
}

function stopPreview() {
  if (emulator) emulator.stop();
  setStatus("Preview stopped", "");
  document.getElementById("btn-run").style.display = "inline-block";
  document.getElementById("btn-stop").style.display = "none";
}

// ─────────────────────────────────────────────
//  BUILD & FLASH (THE MOONSHOT)
// ─────────────────────────────────────────────
function logBuild(msg, type = "") {
  const c = document.getElementById("build-console");
  const line = document.createElement("div");
  line.className = type;
  line.textContent = msg;
  c.appendChild(line);
  c.scrollTop = c.scrollHeight;
}

function setBuildStage(name, state) {
  const el = document.getElementById("stage-" + name);
  if (!el) return;
  el.classList.remove("active", "done", "error");
  if (state) el.classList.add(state);
}

function setBuildProgress(pct, msg) {
  document.getElementById("build-progress").style.width = pct + "%";
  if (msg) document.getElementById("build-msg").textContent = msg;
}

function openBuildModal() {
  // Reset state
  ["compile", "connect", "flash", "done"].forEach(s => setBuildStage(s, ""));
  setBuildProgress(0, "Ready to build");
  document.getElementById("build-console").innerHTML = "";
  document.getElementById("btn-build-start").disabled = false;
  document.getElementById("btn-build-start").textContent = "Start Build & Flash";
  document.getElementById("modal-build").style.display = "flex";
}

async function startBuildAndFlash() {
  if (!editor || !builder) return;
  const src = editor.getValue();
  const funcName = detectEntryFunction(src);
  const appName  = funcName.replace(/^run_/, "") || "my_app";

  document.getElementById("btn-build-start").disabled = true;
  document.getElementById("btn-build-start").textContent = "Building…";

  // ── COMPILE STAGE ──
  setBuildStage("compile", "active");
  setBuildProgress(10, "Submitting source to compile server…");
  logBuild("→ Compile stage", "info");

  let buildResult;
  try {
    buildResult = await builder.build(src, currentType, appName);
    setBuildStage("compile", "done");
    setBuildProgress(50, `Compiled (${buildResult.size} bytes)`);
    logBuild(`✓ Binary received: ${buildResult.size} bytes`, "info");
  } catch (err) {
    setBuildStage("compile", "error");
    logBuild(`✗ ${err.message}`, "err");
    document.getElementById("btn-build-start").disabled = false;
    document.getElementById("btn-build-start").textContent = "Retry";
    return;
  }

  // ── CONNECT STAGE ──
  setBuildStage("connect", "active");
  setBuildProgress(55, "Requesting USB serial port…");
  logBuild("→ Connect stage — select your T-Deck in the browser dialog", "info");

  // ── FLASH STAGE handled inside builder.flash ──
  try {
    await builder.flash(buildResult);
    setBuildStage("connect", "done");
    setBuildStage("flash",   "done");
    setBuildStage("done",    "done");
    setBuildProgress(100, "Flashed and running ✓");
    logBuild("✓ Your app is running on the T-Deck", "info");

    document.getElementById("btn-build-start").textContent = "Build Again";
    document.getElementById("btn-build-start").disabled = false;
  } catch (err) {
    // Distinguish between connect failure and flash failure
    if (err.message.includes("Port") || err.message.includes("cancelled")) {
      setBuildStage("connect", "error");
    } else {
      setBuildStage("connect", "done");
      setBuildStage("flash",   "error");
    }
    logBuild(`✗ ${err.message}`, "err");
    document.getElementById("btn-build-start").disabled = false;
    document.getElementById("btn-build-start").textContent = "Retry";
  }
}

// ─────────────────────────────────────────────
//  INITIALIZATION
// ─────────────────────────────────────────────
function init() {
  // Initialize emulator
  emulator = new PiscesEmulator(document.getElementById("preview-canvas"));
  emulator.consoleLog = logConsole;
  emulator.fpsHook = (fps) => {
    document.getElementById("hw-fps").textContent = fps;
  };

  // Initialize cloud builder
  builder = new LetyBuilder();
  builder.statusHook   = (state, msg) => setBuildProgress(undefined, msg);
  builder.progressHook = (pct) => setBuildProgress(pct);
  builder.consoleLog   = logBuild;

  // Initialize Monaco
  require.config({ paths: { vs: "https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs" } });
  require(["vs/editor/editor.main"], () => {
    monaco.editor.defineTheme("pisces-moon", {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "comment",  foreground: "5a6878", fontStyle: "italic" },
        { token: "keyword",  foreground: "00ff88" },
        { token: "string",   foreground: "ffaa00" },
        { token: "number",   foreground: "aa88ff" },
        { token: "type",     foreground: "4499ff" },
      ],
      colors: {
        "editor.background": "#0d1117",
        "editor.foreground": "#e6edf3",
        "editorLineNumber.foreground": "#3a4555",
        "editor.selectionBackground": "#1a3a5a",
        "editor.lineHighlightBackground": "#161c25",
      }
    });

    editor = monaco.editor.create(document.getElementById("editor"), {
      value: TEMPLATES.builtin_basic.code,
      language: "cpp",
      theme: "pisces-moon",
      fontSize: 13,
      fontFamily: "ui-monospace, 'SF Mono', Menlo, monospace",
      minimap: { enabled: false },
      automaticLayout: true,
      tabSize: 4,
      insertSpaces: true,
      wordWrap: "on",
      lineNumbers: "on",
      renderWhitespace: "selection",
      scrollBeyondLastLine: false,
    });

    // Track cursor position in status bar
    editor.onDidChangeCursorPosition((e) => {
      document.getElementById("status-line").textContent =
        `Line ${e.position.lineNumber}, Col ${e.position.column}`;
    });

    // Add Pisces Moon API completions
    monaco.languages.registerCompletionItemProvider("cpp", {
      provideCompletionItems: (model, position) => {
        const word = model.getWordUntilPosition(position);
        const range = {
          startLineNumber: position.lineNumber,
          endLineNumber: position.lineNumber,
          startColumn: word.startColumn,
          endColumn: word.endColumn,
        };
        const suggestions = [];
        for (const item of PISCES_API_FLAT) {
          if (item.name.startsWith("//")) continue;
          suggestions.push({
            label: item.name,
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: item.name,
            detail: item.category,
            documentation: item.desc,
            range,
          });
        }
        for (const colorName of Object.keys(PISCES_COLORS)) {
          suggestions.push({
            label: colorName,
            kind: monaco.languages.CompletionItemKind.Constant,
            insertText: colorName,
            detail: "Theme color",
            range,
          });
        }
        return { suggestions };
      },
    });

    setStatus("Ready", "success");
    logConsole("Lety v1.0 — Pisces Moon IDE ready", "info");
    logConsole("Click ▶ Run Preview to test your app", "info");
  });

  // Render API panel
  renderAPI();
  renderTemplateGrid();

  // ─── Event handlers ───
  document.getElementById("btn-run").onclick     = runPreview;
  document.getElementById("btn-stop").onclick    = stopPreview;
  document.getElementById("btn-export").onclick  = exportCpp;
  document.getElementById("btn-build").onclick   = openBuildModal;
  document.getElementById("btn-build-start").onclick = startBuildAndFlash;
  document.getElementById("btn-build-cancel").onclick = () =>
    document.getElementById("modal-build").style.display = "none";
  document.getElementById("btn-help").onclick    = () =>
    document.getElementById("modal-help").style.display = "flex";
  document.getElementById("btn-template").onclick = () =>
    document.getElementById("modal-template").style.display = "flex";

  document.getElementById("btn-new").onclick = () => {
    if (editor && confirm("Clear current code?")) {
      editor.setValue(TEMPLATES.builtin_basic.code);
      setStatus("New file", "info");
    }
  };

  document.getElementById("api-filter").oninput = (e) => renderAPI(e.target.value);

  // App type toggle
  document.querySelectorAll(".seg").forEach(btn => {
    btn.onclick = () => {
      document.querySelectorAll(".seg").forEach(b => b.classList.remove("active"));
      btn.classList.add("active");
      currentType = btn.dataset.type;
      const tpl = currentType === "elf" ? TEMPLATES.elf_module : TEMPLATES.builtin_basic;
      currentFunc = tpl.funcName;
      const file = currentType === "elf" ? "my_module.cpp" : "my_app.cpp";
      document.querySelector(".file-item").innerHTML = `<span class="file-icon">📄</span>${file}`;
      document.querySelector(".tab.active").textContent = file;
      if (editor) editor.setValue(tpl.code);
    };
  });

  // Click outside modal to close
  document.querySelectorAll(".modal").forEach(m => {
    m.addEventListener("click", (e) => {
      if (e.target === m) m.style.display = "none";
    });
  });
}

document.addEventListener("DOMContentLoaded", init);
